services:
  postgres:
    image: docker.io/library/postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - keycloak-network

  keycloak:
    image: ghcr.io/scottylabs/keycloak:${KEYCLOAK_VERSION:-main}
    command: start
    environment:
      # Database
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${DB_PASSWORD}

      # Admin credentials
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      # Hostname configuration
      KC_HOSTNAME: idp.scottylabs.org
      KC_HOSTNAME_STRICT: "true"

      # Proxy configuration
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: "true"

      # Debug logging for identity broker
      KC_LOG_LEVEL: "org.keycloak.broker:debug"
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - keycloak-network

volumes:
  postgres_data:

networks:
  keycloak-network:
    driver: bridge
